// File generated by FlutterFire CLI (manually updated for FlutterFire >=4.0.0)
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCApOFuPvfyVpuexYsPsNf1w_2V2Eez4xY',
    appId: '1:493528129664:web:742f115371e5ee4132c665',
    messagingSenderId: '493528129664',
    projectId: 'appsmart-457c0',
    authDomain: 'appsmart-457c0.firebaseapp.com',
    storageBucket: 'appsmart-457c0.firebasestorage.app',
    measurementId: 'G-3TGGFV5WX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5MfwLZbM0oJsEz8AfnF_vyEsJLFaRQcI',
    appId: '1:493528129664:android:dff244704e353c6d32c665',
    messagingSenderId: '493528129664',
    projectId: 'appsmart-457c0',
    storageBucket: 'appsmart-457c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnvITVhdIB5mG_d8m_arAVPz65xGMYnso',
    appId: '1:493528129664:ios:e51c94b05d05497632c665',
    messagingSenderId: '493528129664',
    projectId: 'appsmart-457c0',
    storageBucket: 'appsmart-457c0.firebasestorage.app',
    androidClientId:
        '493528129664-7490bp04lrhfa0r8mdbsoufiil8n7r64.apps.googleusercontent.com',
    iosClientId:
        '493528129664-2g58c1ijjfkvabeqtg56h41fd9h23hfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.devop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnvITVhdIB5mG_d8m_arAVPz65xGMYnso',
    appId: '1:493528129664:ios:e51c94b05d05497632c665',
    messagingSenderId: '493528129664',
    projectId: 'appsmart-457c0',
    storageBucket: 'appsmart-457c0.firebasestorage.app',
    androidClientId:
        '493528129664-7490bp04lrhfa0r8mdbsoufiil8n7r64.apps.googleusercontent.com',
    iosClientId:
        '493528129664-2g58c1ijjfkvabeqtg56h41fd9h23hfu.apps.googleusercontent.com',
    iosBundleId: 'com.example.devop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCApOFuPvfyVpuexYsPsNf1w_2V2Eez4xY',
    appId: '1:493528129664:web:9259f182ce65b30332c665',
    messagingSenderId: '493528129664',
    projectId: 'appsmart-457c0',
    authDomain: 'appsmart-457c0.firebaseapp.com',
    storageBucket: 'appsmart-457c0.firebasestorage.app',
    measurementId: 'G-CN2GSN95BE',
  );
}

// פונקציה לקבלת FirebaseOptions לפי הפלטפורמה
FirebaseOptions getFirebaseOptions() {
  if (kIsWeb) return DefaultFirebaseOptions.web;

  switch (defaultTargetPlatform) {
    case TargetPlatform.android:
      return DefaultFirebaseOptions.android;
    case TargetPlatform.iOS:
      return DefaultFirebaseOptions.ios;
    case TargetPlatform.macOS:
      return DefaultFirebaseOptions.macos;
    case TargetPlatform.windows:
      return DefaultFirebaseOptions.windows;
    default:
      throw UnsupportedError('This platform is not supported');
  }
}
